import type { Rec, SeedSong } from "./types";

export const SEEDS: SeedSong[] = [
  { id: "s1", title: "Feel No Ways", artist: "Drake", img: "https://lastfm.freetls.fastly.net/i/u/675aedda266d84d3fdcb008326bc3b10" },
  { id: "s2", title: "Attracted to You", artist: "PinkPantheress", img: "https://lastfm.freetls.fastly.net/i/u/11695ed0b453ddae38418e45d5441470" },
  { id: "s3", title: "Jungle", artist: "Drake", img: "https://lastfm.freetls.fastly.net/i/u/f4cf524e4b46f72ebe75bbf1e0873b42" },
  { id: "s4", title: "Television / So Far So Good", artist: "Rex Orange County", img: "https://lastfm.freetls.fastly.net/i/u/c869ac799047020ad305d589f44bbe75" },
  { id: "s5", title: "Helmet", artist: "Steve Lacy", img: "https://lastfm.freetls.fastly.net/i/u/12dcf1122cccf14bd8d943480d04cd58" },
  { id: "s6", title: "Noises", artist: "PinkPantheress", img: "https://lastfm.freetls.fastly.net/i/u/5edfc17276a2c1f445f41faf2c9da1be" },
  { id: "s7", title: "Ultralight Beam", artist: "Kanye West", img: "https://lastfm.freetls.fastly.net/i/u/8c6af1315c66631bad022085c7992b34" },
  { id: "s8", title: "3005", artist: "Childish Gambino", img: "https://lastfm.freetls.fastly.net/i/u/0f636525495f1458c7c55f238eb8e27d" },
  { id: "s9", title: "Company", artist: "Drake", img: "https://lastfm.freetls.fastly.net/i/u/f4cf524e4b46f72ebe75bbf1e0873b42" },
  { id: "s10", title: "Take me home", artist: "PinkPantheress", img: "https://lastfm.freetls.fastly.net/i/u/67dfb2d6147fad4604054ae48d44ab88" },
  { id: "s11", title: "Pray 4 Love (feat. The Weeknd)", artist: "Travis Scott", img: "https://lastfm.freetls.fastly.net/i/u/29f1a6ef4c129b3a4ddbdd34d4e757d0" },
  { id: "s12", title: "L.E.S.", artist: "Childish Gambino", img: "https://lastfm.freetls.fastly.net/i/u/d2c51831aa2b59b93c7e56b29efbbcf6" },
  { id: "s13", title: "Close to You", artist: "Frank Ocean", img: "https://lastfm.freetls.fastly.net/i/u/82c92f044b27db86328ed6be3f8a735a" },
  { id: "s14", title: "In the Night", artist: "The Weeknd", img: "https://lastfm.freetls.fastly.net/i/u/9ea87cbc2865f38105cc1aecc49bfa82" },
  { id: "s15", title: "Sunshine (feat. Fousheé)", artist: "Steve Lacy", img: "https://lastfm.freetls.fastly.net/i/u/12dcf1122cccf14bd8d943480d04cd58" },
];

export const RECS: Rec[] = [
  {
    id: "r1",
    title: "Gravity (feat. Tyler, The Creator)",
    artist: "Brent Faiyaz",
    album: "WASTELAND",
    img: "https://4kwallpapers.com/images/walls/thumbs_3t/13794.png",
    matchPct: 95,
    why: "You love smooth R&B and creative collaborations, and this track blends both.",
    tags: ["R&B", "Collab"],
    bpm: 120,
    genre: "R&B",
    length: "3:46",
    snippet: "/snippets/Gravity.mp3",
  },
  {
    id: "r2",
    title: "Pink + White",
    artist: "Frank Ocean",
    album: "Blonde",
    img: "https://i.redd.it/1r0pklck1vpy.png",
    matchPct: 92,
    why: "Dreamy production and emotional vocals match your taste for genre-blending and introspective music.",
    tags: ["R&B", "Alt"],
    bpm: 135,
    genre: "R&B",
    length: "3:04",
    snippet: "/snippets/Pink+White.mp3",
  },
  {
    id: "r3",
    title: "Boredom (feat. Rex Orange County & Anna of the North)",
    artist: "Tyler, The Creator",
    album: "Flower Boy",
    img: "https://preview.redd.it/i-widened-the-flower-boy-album-cover-for-pc-wallpaper-v0-2osyg6q62o8e1.png?auto=webp&s=8da6f55e897db22fbe6d5a415dacc2fc1ac69d51",
    matchPct: 90,
    why: "You enjoy alternative hip-hop and unique features, and this track is a perfect fit.",
    tags: ["Hip-Hop", "Alternative"],
    bpm: 80,
    genre: "Hip-Hop",
    length: "4:16",
    snippet: "/snippets/Boredom.mp3",
  },
  {
    id: "r4",
    title: "Instant Crush (feat. Julian Casablancas)",
    artist: "Daft Punk",
    album: "Random Access Memories",
    img: "https://img1.wallspic.com/previews/6/0/4/6/5/156406/156406-daft_punk-random_access_memories-get_lucky-disco-metal-x350.jpg",
    matchPct: 88,
    why: "Synth-driven pop and strong vocal hooks are a staple in your listening.",
    tags: ["Pop", "Synth"],
    bpm: 110,
    genre: "Pop",
    length: "5:37",
    snippet: "/snippets/InstantCrush.mp3",
  },
  {
    id: "r5",
    title: "327 (feat. Tyler, The Creator & Billie Essco)",
    artist: "Westside Gunn, Joey Bada$$, Tyler, The Creator",
    album: "Pray for Paris",
    img: "https://media.pitchfork.com/photos/652852d088a5650287adb2df/16:9/w_1280,c_limit/Westside-Gunn-Pray-for-Paris.jpg",
    matchPct: 86,
    why: "Lush, jazzy production and a stacked feature list fit your taste for creative hip-hop collaborations.",
    tags: ["Hip-Hop", "Jazz Rap"],
    bpm: 74,
    genre: "Hip-Hop",
    length: "4:36",
    snippet: "/snippets/327.mp3",
  },
  {
    id: "r6",
    title: "Redbone",
    artist: "Childish Gambino",
    album: "Awaken, My Love!",
    img: "https://upload.wikimedia.org/wikipedia/en/1/10/Childish_Gambino_-_Awaken%2C_My_Love%21.png",
    matchPct: 84,
    why: "Funk-leaning R&B with vintage production fits your sonic profile.",
    tags: ["R&B", "Funk"],
    bpm: 80,
    genre: "Funk",
    length: "5:27",
  },
  {
    id: "r7",
    title: "Sundress",
    artist: "A$AP Rocky",
    album: "Sundress",
    img: "https://upload.wikimedia.org/wikipedia/en/e/e5/ASAP_Rocky_%E2%80%93_Sundress.png",
    matchPct: 82,
    why: "Sample-heavy alt hip-hop you've been gravitating toward.",
    tags: ["Hip-Hop", "Alt"],
    bpm: 95,
    genre: "Hip-Hop",
    length: "3:08",
  },
  {
    id: "r8",
    title: "Self Control",
    artist: "Frank Ocean",
    album: "Blonde",
    img: "https://upload.wikimedia.org/wikipedia/en/a/a0/Blonde_-_Frank_Ocean.jpeg",
    matchPct: 81,
    why: "Layered vocals and introspective lyrics align with your DNA.",
    tags: ["R&B", "Alt"],
    bpm: 88,
    genre: "R&B",
    length: "4:09",
  },
  {
    id: "r9",
    title: "EARFQUAKE",
    artist: "Tyler, The Creator",
    album: "IGOR",
    img: "https://upload.wikimedia.org/wikipedia/en/5/51/Igor_-_Tyler%2C_the_Creator.jpg",
    matchPct: 79,
    why: "High-energy synth-pop with hip-hop crossover appeal.",
    tags: ["Hip-Hop", "Pop"],
    bpm: 80,
    genre: "Hip-Hop",
    length: "2:51",
  },
  {
    id: "r10",
    title: "Hotline Bling",
    artist: "Drake",
    album: "Views",
    img: "https://upload.wikimedia.org/wikipedia/en/a/af/Drake_-_Views_cover.jpg",
    matchPct: 77,
    why: "Drake staples weight heavily in your listening history.",
    tags: ["R&B", "Pop"],
    bpm: 135,
    genre: "R&B",
    length: "4:27",
  },
  {
    id: "r11",
    title: "Sunflower",
    artist: "Post Malone & Swae Lee",
    album: "Spider-Man: Into the Spider-Verse",
    img: "https://upload.wikimedia.org/wikipedia/en/2/2f/Spider-Man_Into_the_Spider-Verse_%28Soundtrack_From_%26_Inspired_by_the_Motion_Picture%29_cover.jpg",
    matchPct: 75,
    why: "Melodic rap-pop that fits your hook-driven taste.",
    tags: ["Pop", "Rap"],
    bpm: 90,
    genre: "Pop",
    length: "2:38",
  },
  {
    id: "r12",
    title: "Sweet Life",
    artist: "Frank Ocean",
    album: "channel ORANGE",
    img: "https://upload.wikimedia.org/wikipedia/en/2/28/Channel_ORANGE.jpg",
    matchPct: 74,
    why: "Soulful R&B with experimental edges — your sweet spot.",
    tags: ["R&B", "Soul"],
    bpm: 100,
    genre: "R&B",
    length: "4:23",
  },
  {
    id: "r13",
    title: "Dawn (Better Days)",
    artist: "Joji",
    album: "BALLADS 1",
    img: "https://upload.wikimedia.org/wikipedia/en/6/6a/Joji_%E2%80%93_Ballads_1.png",
    matchPct: 72,
    why: "Lo-fi production with emotional weight.",
    tags: ["Lo-fi", "Indie"],
    bpm: 92,
    genre: "Lo-fi",
    length: "3:14",
  },
  {
    id: "r14",
    title: "After Hours",
    artist: "The Weeknd",
    album: "After Hours",
    img: "https://upload.wikimedia.org/wikipedia/en/c/c1/The_Weeknd_-_After_Hours.png",
    matchPct: 70,
    why: "Dark pop atmospherics — recurring in your night sessions.",
    tags: ["Pop", "Dark"],
    bpm: 108,
    genre: "Dark Pop",
    length: "6:01",
  },
  {
    id: "r15",
    title: "Coffee",
    artist: "BROCKHAMPTON",
    album: "GINGER",
    img: "https://upload.wikimedia.org/wikipedia/en/a/a0/Brockhampton_-_Ginger.png",
    matchPct: 68,
    why: "Genre-blurring hip-hop collectives match your eclectic taste.",
    tags: ["Hip-Hop", "Alt"],
    bpm: 105,
    genre: "Hip-Hop",
    length: "4:17",
  },
];

export const RADAR_DATA = [
  { attr: "Tempo", v: 82 },
  { attr: "Valence", v: 60 },
  { attr: "Energy", v: 77 },
  { attr: "Dance", v: 68 },
  { attr: "Acoustic", v: 32 },
  { attr: "Live", v: 38 },
];

export const SUGGESTED_PLAYLISTS = [
  {
    id: "p1",
    title: "Late Night Drives",
    by: "Alex Liu",
    tracks: 24,
    img: "https://picsum.photos/seed/late-night-drives/400/400",
  },
  {
    id: "p2",
    title: "Workout Pump",
    by: "Maya Kwan",
    tracks: 38,
    img: "https://picsum.photos/seed/workout-pump/400/400",
  },
  {
    id: "p3",
    title: "Sunday Chill",
    by: "Ryan Jo",
    tracks: 19,
    img: "https://picsum.photos/seed/sunday-chill/400/400",
  },
  {
    id: "p4",
    title: "Coffee Shop Vibes",
    by: "Sam Park",
    tracks: 31,
    img: "https://picsum.photos/seed/coffee-shop-vibes/400/400",
  },
];

export const ATTRS = [
  { label: "Tempo", value: 82, color: "#A855F7" },
  { label: "Valence", value: 60, color: "#A855F7" },
  { label: "Energy", value: 77, color: "#14F5D0" },
  { label: "Danceability", value: 68, color: "#14F5D0" },
  { label: "Acousticness", value: 32, color: "#6366F1" },
  { label: "Liveness", value: 38, color: "#6366F1" },
];
